### ISSUE TITLE
Avoid implicit type conversions

### ISSUE THREAD

**Issue by zannain** [sidrikblal/jammming#2]
Javascript isn't a strongly typed language and so it allows for implicitly type conversion which isn't considered [best practice](http://2ality.com/2013/04/quirk-implicit-conversion.html). So you may be able to get away with using [`isRemoval = 'false'`](https://github.com/sidrikblal/jammming/blob/master/src/components/SearchResults/SearchResults.js#L11) here but I would recommend using `isRemoval = {false}` so you are explicitly casting the value to be a Boolean.

**Comment by sidrikblal** [comment]
Better to explicitly setting the value to a Boolean. thx
