### ISSUE TITLE
ES6 Object Destructuring

### ISSUE THREAD

**Issue by zannain** [sidrikblal/jammming#5]
A neat trick that was introduced with ES6 was [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring). You can use destructuring to refactor and reduce some of the code in your application. A simple example is taking the [`updatePlaylistName`](https://github.com/sidrikblal/jammming/blob/master/src/components/App/App.js#L58-L63) method

_Before_
```jsx
updatePlaylistName(name){
	this.setState({playlistName: name});
}
```

_After_
```jsx
updatePlaylistName(playlistName){
	this.setState({playlistName});
}
```

**Comment by sidrikblal** [comment]
cool. neat. thx
