### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by zannain** [sidrikblal/jammming#6]
**Awesome work with this application!** _Props_ for adding descriptions to every method and using consistent indentation and formatting and not leaving any debug statements comment out or showing up in the console. 

Good work on integrating the Spotify API and populating the results on keypress! I would recommend getting rid of some of those errors that are appearing in the console when searching. An application pushed to production should not have errors cluttering up the console.  

React is a library that has a lot of development behind it so I recommend using newsletters to keep up with the changes. Check out this [newsletter that was designed for developers](https://cooperpress.com/). Now that you have a solid foundation in React, you might consider learning Redux which supplements React.[ Here's a resource to get you started](https://learnredux.com/). **_Keep up the great work Sidrik!!_**

**Comment by sidrikblal** [comment]
thx for your kind words zannain and for your advice and link to learn Redux. Learning never stops!
Which errors are you referring to in your 2nd paragraph? This screenshot shows the only thing that my console shows:
![2018-05-04_10h08_59](https://user-images.githubusercontent.com/37372237/39618354-a133f6fe-4f83-11e8-9106-e79ffb860c1d.png)
Is that considered as an error?
thx

**Comment by zannain** [comment]
Hey Sid, I was referring to when you are making a search. I've attached a screenshot below. 

![image](https://user-images.githubusercontent.com/24375741/39677861-2c54558a-5150-11e8-8585-d4105c2949bd.png)
